# Table of Contents
 <p><div class="lev1"><a href="#NumPy-配列の生成-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy 配列の生成</a></div><div class="lev2"><a href="#np.array()関数による生成-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>np.array()関数による生成</a></div><div class="lev2"><a href="#その他の関数による生成-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>その他の関数による生成</a></div><div class="lev2"><a href="#NumPy配列の属性と要素の参照-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>NumPy配列の属性と要素の参照</a></div><div class="lev3"><a href="#dtypeについて-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>dtypeについて</a></div><div class="lev3"><a href="#要素の参照-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>要素の参照</a></div>

In [27]:
import numpy as np
import scipy as sp
import sklearn

# NumPy 配列の生成

np.ndarrayを生成する

## np.array()関数による生成

In [16]:
a = np.array([1,2,3])

In [7]:
a

array([1, 2, 3])

In [11]:
a = np.array([[1.5, 0], [2, 3]])

In [12]:
a

array([[ 1.5,  0. ],
       [ 2. ,  3. ]])

## その他の関数による生成

In [13]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [14]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [19]:
#要素の値は不定
np.empty((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [21]:
a = np.array([[1,2,3],[4,5,6]])

In [23]:
#既存の配列と同じ大きさの配列を生成
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## NumPy配列の属性と要素の参照

### dtypeについて

In [28]:
a = np.array([1,2,3])

In [29]:
a.dtype

dtype('int64')

In [30]:
a = np.array([1,2,3], dtype=np.float)

In [31]:
a.dtype

dtype('float64')

In [32]:
a = np.array(a, dtype=np.complex)

In [33]:
a

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [34]:
a = a.astype(np.float)

/Users/KYO/.local/lib/python3.4/site-packages/ipykernel/__main__.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  if __name__ == '__main__':


In [35]:
a

array([ 1.,  2.,  3.])

### 要素の参照

In [38]:
a = np.array([1,2,3,4,5], dtype=float)

In [39]:
a[3]

4.0

In [41]:
a = np.array([[11,12,13],[21,22,23]])

In [42]:
a.shape

(2, 3)

In [43]:
a[1,2]

23